/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Contact': RouteRecordInfo<
      '/Contact',
      '/Contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Games/ClassSleep': RouteRecordInfo<
      '/Games/ClassSleep',
      '/Games/ClassSleep',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Games/Index': RouteRecordInfo<
      '/Games/Index',
      '/Games/Index',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Home': RouteRecordInfo<
      '/Home',
      '/Home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/News': RouteRecordInfo<
      '/News',
      '/News',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotFound': RouteRecordInfo<
      '/NotFound',
      '/NotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Settings': RouteRecordInfo<
      '/Settings',
      '/Settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Text': RouteRecordInfo<
      '/Text',
      '/Text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/View': RouteRecordInfo<
      '/View',
      '/View',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/Contact.vue': {
      routes:
        | '/Contact'
      views:
        | never
    }
    'src/pages/Games/ClassSleep.vue': {
      routes:
        | '/Games/ClassSleep'
      views:
        | never
    }
    'src/pages/Games/Index.vue': {
      routes:
        | '/Games/Index'
      views:
        | never
    }
    'src/pages/Home.vue': {
      routes:
        | '/Home'
      views:
        | never
    }
    'src/pages/News.vue': {
      routes:
        | '/News'
      views:
        | never
    }
    'src/pages/NotFound.vue': {
      routes:
        | '/NotFound'
      views:
        | never
    }
    'src/pages/Settings.vue': {
      routes:
        | '/Settings'
      views:
        | never
    }
    'src/pages/Text.vue': {
      routes:
        | '/Text'
      views:
        | never
    }
    'src/pages/View.vue': {
      routes:
        | '/View'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
